name: Rust tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: |
          mv src src-frontend
          mv src-tauri/* .
      - uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Build
        run: cargo build --tests --workspace
      - name: Run tests
        # Profile "ci" is configured in .config/nextest.toml
        run: cargo nextest run --workspace --profile ci
        env:
          CANVAS_TOKEN: ${{ env.CANVAS_TOKEN }}
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.os }}.xml
          path: target/nextest/ci/junit.xml
